name: Release Builder Demo

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y cmake rpm dpkg-dev
      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build GoogleTest
        run: cmake --build build/_deps/googletest-build
      - name: Build Builder Demo
        run: cmake --build build --target builder_demo --config Release
      - name: Build Tests
        run: cmake --build build --target builder_tests --config Release
      - name: Run Tests
        run: ctest --test-dir build --output-on-failure
      - name: Install only app
        run: cmake --install build --prefix build/install
      - name: Package
        run: cd build && cpack -G DEB && cpack -G RPM && cpack -G ZIP
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.deb
            build/*.rpm
            build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
